# https://github.com/Mte90/GBAATM-Rebirth/blob/master/.github/workflows/main.yml

name: Release on Push
on:
  push:
    #tags:
     # - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    # Pick a branch to generate a new build
    #branches: [ master ]
  
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: ${{ runner.os }}-Qt-${{ needs.create-release.outputs.version }}
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
    # This is required or cannot compile it
        arch: win64_mingw73
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
        version: '6.3.2'

    - name: CmakeBuild
      run: mkdir build/out && cd build && cmake -DCMAKE_PREFIX_PATH=C:\Qt\6.3.2\mingw73_64 -S ../ -B .
    - name: MinGW libraries 
      run: cp "..\Qt\6.3.2\mingw73_64\bin\libgcc_s_seh-1.dll" ".\build\out" && cp "..\Qt\6.3.2\mingw73_64\bin\libstdc++-6.dll" ".\build\out" && cp "..\Qt\6.3.2\mingw73_64\bin\libwinpthread-1.dll" ".\build\out"
    - name: Build
    # windeployqt is required to find all the libraries, don't find the C++
      run: cd build && make && mv ./release/comPortScanner.exe ./out && windeployqt --compiler-runtime --no-svg --no-opengl-sw --no-angle --no-system-d3d-compiler ./out/comPortScanner.exe
    - name: Package project 
      # Path to the build is different in windows, also the command
      run: Compress-Archive -Path "build/out/*" -DestinationPath windows.zip

    - uses: actions/upload-artifact@v3
      with:
        name: windowsExe
        path: ./windows.zip
